// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: testernet/kyc/tx.proto

package kyc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName     = "/testernet.kyc.Msg/UpdateParams"
	Msg_CreateKycAddress_FullMethodName = "/testernet.kyc.Msg/CreateKycAddress"
	Msg_UpdateKycAddress_FullMethodName = "/testernet.kyc.Msg/UpdateKycAddress"
	Msg_DeleteKycAddress_FullMethodName = "/testernet.kyc.Msg/DeleteKycAddress"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	CreateKycAddress(ctx context.Context, in *MsgCreateKycAddress, opts ...grpc.CallOption) (*MsgCreateKycAddressResponse, error)
	UpdateKycAddress(ctx context.Context, in *MsgUpdateKycAddress, opts ...grpc.CallOption) (*MsgUpdateKycAddressResponse, error)
	DeleteKycAddress(ctx context.Context, in *MsgDeleteKycAddress, opts ...grpc.CallOption) (*MsgDeleteKycAddressResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateKycAddress(ctx context.Context, in *MsgCreateKycAddress, opts ...grpc.CallOption) (*MsgCreateKycAddressResponse, error) {
	out := new(MsgCreateKycAddressResponse)
	err := c.cc.Invoke(ctx, Msg_CreateKycAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateKycAddress(ctx context.Context, in *MsgUpdateKycAddress, opts ...grpc.CallOption) (*MsgUpdateKycAddressResponse, error) {
	out := new(MsgUpdateKycAddressResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateKycAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteKycAddress(ctx context.Context, in *MsgDeleteKycAddress, opts ...grpc.CallOption) (*MsgDeleteKycAddressResponse, error) {
	out := new(MsgDeleteKycAddressResponse)
	err := c.cc.Invoke(ctx, Msg_DeleteKycAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	CreateKycAddress(context.Context, *MsgCreateKycAddress) (*MsgCreateKycAddressResponse, error)
	UpdateKycAddress(context.Context, *MsgUpdateKycAddress) (*MsgUpdateKycAddressResponse, error)
	DeleteKycAddress(context.Context, *MsgDeleteKycAddress) (*MsgDeleteKycAddressResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) CreateKycAddress(context.Context, *MsgCreateKycAddress) (*MsgCreateKycAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKycAddress not implemented")
}
func (UnimplementedMsgServer) UpdateKycAddress(context.Context, *MsgUpdateKycAddress) (*MsgUpdateKycAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKycAddress not implemented")
}
func (UnimplementedMsgServer) DeleteKycAddress(context.Context, *MsgDeleteKycAddress) (*MsgDeleteKycAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKycAddress not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateKycAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateKycAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateKycAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateKycAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateKycAddress(ctx, req.(*MsgCreateKycAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateKycAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateKycAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateKycAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateKycAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateKycAddress(ctx, req.(*MsgUpdateKycAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteKycAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteKycAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteKycAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeleteKycAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteKycAddress(ctx, req.(*MsgDeleteKycAddress))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "testernet.kyc.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateKycAddress",
			Handler:    _Msg_CreateKycAddress_Handler,
		},
		{
			MethodName: "UpdateKycAddress",
			Handler:    _Msg_UpdateKycAddress_Handler,
		},
		{
			MethodName: "DeleteKycAddress",
			Handler:    _Msg_DeleteKycAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testernet/kyc/tx.proto",
}
